presubmits:
  kubernetes-sigs/aws-load-balancer-controller:
  - name: pull-aws-load-balancer-controller-lint
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        command:
        - runner.sh
        args:
        - make
        - lint
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
    annotations:
      testgrid-dashboards: provider-aws-load-balancer-controller
      testgrid-tab-name: lint
      description: aws load balancer controller code lint
      testgrid-num-columns-recent: '30'
  - name: pull-aws-load-balancer-controller-unit-test
    cluster: k8s-infra-prow-build
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
        resources:
          limits:
            cpu: 6
            memory: 4Gi
          requests:
            cpu: 6
            memory: 4Gi
    annotations:
      testgrid-dashboards: provider-aws-load-balancer-controller
      testgrid-tab-name: unit test
      description: aws load balancer controller unit tests
      testgrid-num-columns-recent: '30'
  - name: pull-aws-load-balancer-controller-e2e-test
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-aws-ssh: "true"
      preset-aws-credential-aws-oss-testing: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230727-ea685f8747-master
        command:
        - runner.sh
        args:
        - make
        - e2e-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: provider-aws-load-balancer-controller
      testgrid-tab-name: e2e test
      description: aws load balancer controller e2e tests
      testgrid-num-columns-recent: '30'
